- name: Install vector
  hosts: vector
  handlers:
    - name: Restart vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/0.35.0/vector-0.35.0-1.x86_64.rpm
        dest: ./vector-0.35.0-1.x86_64.rpm

    - name: Install vector
      become: true
      ansible.builtin.yum:
        name: vector-0.35.0-1.x86_64.rpm

    - name: Copy vector config
      become: true
      ansible.builtin.template:
        src: templates/vector.j2
        dest: /etc/vector/vector.yaml
      notify: Restart vector service
    
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers