apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "while true; do echo 'Hello from busybox' >> /opt/output.txt; sleep 5; done"]
          volumeMounts:
            - name: local-storage
              mountPath: /opt
        - name: multitool
          image: wbitt/network-multitool
          command: ["sh", "-c", "tail -f /opt/output.txt"]
          volumeMounts:
            - name: local-storage
              mountPath: /opt
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: local-pvc