---
- name: Install epel-release + git for lighthouse
  ansible.builtin.yum:
    name:
      - epel-release
      - git

- name: Install nginx
  ansible.builtin.yum:
    name:
      - nginx

- name: Creates nginx site directory
  ansible.builtin.file:
    path: "{{ nginx_path }}"
    state: directory

- name: Get lighthouse distrib
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse.git
    dest: "{{ nginx_path }}/lighthouse"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy nginx config
  ansible.builtin.template:
    src: templates/nginx.j2
    dest: /etc/nginx/nginx.conf
  notify: Reload nginx conf lighthouse

- name: Create lighthouse config
  ansible.builtin.template:
    src: templates/lighthouse.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: Reload nginx conf lighthouse