---
- name: Install openssl-devel
  ansible.builtin.yum:
    name: 
      - openssl-devel
      - ca-certificates

- name: Upgrade ca-certificates
  ansible.builtin.command: yum -y update ca-certificates

- name: Get vector distrib
  ansible.builtin.get_url:
    url: https://packages.timber.io/vector/0.35.0/vector-0.35.0-1.x86_64.rpm
    dest: ./vector-0.35.0-1.x86_64.rpm
    
- name: Install vector
  ansible.builtin.yum:
    name: https://packages.timber.io/vector/0.35.0/vector-0.35.0-1.x86_64.rpm

- name: Copy vector config
  ansible.builtin.template:
    src: templates/vector.j2
    dest: /etc/vector/vector.yaml
