---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-netology-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80
            name: http-port
          - containerPort: 443
            name: https-port
        - name: network-multitool
          image: wbitt/network-multitool
          env:
          - name: HTTP_PORT
            value: "1180"
          - name: HTTPS_PORT
            value: "11443"
          ports:
          - containerPort: 1180
            name: http-port
          - containerPort: 11443
            name: https-port
---
apiVersion: v1
kind: Service
metadata:
  name: my-netology-service
spec:
  ports:
    - name: netology-nginx
      port: 80
      protocol: TCP
      targetPort: 80
    - name: netology-multitool
      port: 8080
      protocol: TCP
      targetPort: 1180
  selector:
    app: my-app
---
apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool