---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: pod-with-app
  namespace: netology
spec:
  containers:
  - name: myapp
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
