apiVersion: v1
kind: Service
metadata:
  name: my-app-nodeport
  namespace: homework
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - protocol: TCP
      name: nginx-nodeport
      port: 80
      nodePort: 30080
      targetPort: 80
    - protocol: TCP
      name: multitool-nodeport
      port: 8080
      nodePort: 30880
      targetPort: 8080